[target.riscv32imc-unknown-none-elf]
# runner = "espflash flash --monitor --chip esp32c3 --log-format defmt"
runner = "espflash flash --monitor --chip esp32c3"

[env]
DEFMT_LOG = "info"

# order for debug: Tlinkall Tdefmt
# makes esphlash happy. Fixes this error:
# Error: espflash::monitor::defmt::table_parse_failed
#   × failed to demangle defmt symbol `__global_pointer$`: expected value at line
#   │ 1 column 1
#   ╰─▶ Failed to parse defmt data

# order for life:  Tdefmt Tlinkall
# in opposite order freezes sometimes it no debugger attached.
# push hard reset and see freeze to reproduce

[build]
rustflags = [

  "-C",
  "link-arg=-Tdefmt.x",


  "-C",
  "link-arg=-Tlinkall.x",


  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",


  # until nightly
  # "-Z",
  #"stack-protector=all",
]


# [target.'cfg(target_arch = "xtensa")']
# runner = "espflash flash --monitor"
# rustflags = [
#   # GNU LD
#   "-C",
#   "link-arg=-Wl,-Tlinkall.x",
#   "-C",
#   "link-arg=-Tdefmt.x",
#   "-C",
#   "link-arg=-nostartfiles",

#   # LLD
#   # "-C", "link-arg=-Tlinkall.x",
#   # "-C", "linker=rust-lld",
# ]


target = "riscv32imc-unknown-none-elf"


[unstable]
build-std = ["alloc", "core"]
